### ISSUE TITLE
Suggestions via Santos

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#102]
Vapor is sweeet!
Sent: Sun Sep 08, 2013 6:35 pm
by Santos

Hey!

Vapor is such a good idea, congrats for thinking of it and making it!

If someone is interested in trying LÖVE, I bet the first thing most people will want to do is find some games which were made in it. They'll go to the wiki page for games and... find that most of them don't run in the latest version, and they'll find it missing a lot of cool games (Your games being an exception to these things!). With Vapor it's just so ridiculously easy to find and try out games with it.

So yeah, just wanted to say well done, and I was wondering, would you mind my two cents on the design?

---

Re: Vapor is sweeet!
Sent: Tue Sep 10, 2013 7:43 pm 
From: Santos 
To: josefnpat 

Haha, I don't think the design is horrible at all, and I understand it's a work-in-progress, and I'm sure some of the following points have been thought about before or are terrible ideas, but hey, I hope to help if I can. :P

The way the screenshots scroll left and right can take a lot of time if the games are far apart, and it's maybe not the most pleasant visual sensation.
When Vapor is loaded the first game on the list is "selected" (display its screenshot and information), however it's not highlighted in the scroll-box-thing.
When selecting a game from the list, and moving to a different tab and selecting a different game, and then moving back to the previous tab, the previously selected game is still highlighted.
The icons to the left of the Download/Play button could be a bit confusing since the other icons in the interface are buttons, whereas these are visual indicators. Downloaded and not-downloaded games are already differentiated by the different labels on the Download/Play button, but if this isn't visually different enough, perhaps there could be some other way.
The delete button is still available even when the game is not installed.
The tooltips for the tabs and the Download/Play button don't really give much useful information.
The tooltips for the tabs are in static positions, whereas the tooltips for the Download/Play button and the icon-button-things follow the cursor.
The font used for the description isn't the easiest to read.
The "Application" button which flips the order of the games is maybe not so useful. Also, when it's pressed, the list is sorted by a different order, with the starting-with-lower-case-name "trAInsported" and the top/bottom.
Arrow keys can't be used to move up and down the list.
Alt-F4 doesn't close the window on Windows.
Perhaps there could be an indication if a game is new or updated?
I had an idea for the games list: Instead of having three tabs, maybe there could be one list, with the downloaded games at the top, and the not-downloaded games underneath, and some sort of visual way to tell them apart, and the downloaded games are sorted by time-last-played, which kind of "replace" the concept of favourites. Just an idea! :P
The games list could use more vertical space.
In the old Vapor I really liked how you could scroll through the game screenshots quickly and play games with one click.
I've heard talk of supporting older versions of LÖVE, but maybe effort would be better spent creating compatibility layers, conversion scripts and migration guides so that all LÖVE games could benefit from being compatible with the latest version?
I don't really think a rating system would be so cool, since... you know... all the games are free, and all it takes to find out if you like a game is to look at the screenshot and download it and see for yourself. And I don't think being at the bottom of the list is going to make the creator feel that great. And it could just result in the lowest common denominator bubbling to the top.

**Comment by qaisjp** [comment]
Santos, I anticipate that the ability to load old games running on old version of love would involve vapor downloading the latest compatible build and then running the .love on that build.

Tabs are better, this allows the user to get quicker access to the games they download instead of hunting it down in a long list.

The sorting using the arrow on the header is important for sorting.

The games could use more vertical space :+1: 

Alt+F4 is easily implementable and indication about updated games are good ideas.

**Comment by Yonaba** [comment]
Hi all, 
I would just like to point that, for some obvious reasons, this issue will not be productive.
_Too much aspects are discussed at the same time_.
I am suggesting that @josefnpat should identity the key points from Santos's suggestions on which there is definitely an open room for debate, and then open a new issue for each one.

Regards,
Roland.

**Comment by qaisjp** [comment]
I agree with Roland Yonaba :+1:

**Comment by josefnpat** [comment]
@Yonaba @qaisjp Thanks for weighing in guys, it will help me figure out what topics are important and which ones aren't. Once I spend some time reviewing this, and determining the new design  #70 , I think we can start opening new tickets based on this.

**Comment by josefnpat** [comment]
This is rather old, so I will pick out relevant thoughts and make tickets out of them.

> The way the screenshots scroll left and right can take a lot of time if the games are far apart, and it's maybe not the most pleasant visual sensation.

This is documented in #87

> When Vapor is loaded the first game on the list is "selected" (display its screenshot and information), however it's not highlighted in the scroll-box-thing.
> When selecting a game from the list, and moving to a different tab and selecting a different game, and then moving back to the previous tab, the previously selected game is still highlighted.
> Arrow keys can't be used to move up and down the list.

These seem like a @NikolaiResokav question. We have nested scrollboxes with tabs. Is the selection something in the lists something that can be changed programatically?

> The icons to the left of the Download/Play button could be a bit confusing since the other icons in the interface are buttons, whereas these are visual indicators. Downloaded and not-downloaded games are already differentiated by the different labels on the Download/Play button, but if this isn't visually different enough, perhaps there could be some other way.

Totally legit. #119

> The delete button is still available even when the game is not installed.

Totally legit. #118

> The tooltips for the tabs and the Download/Play button don't really give much useful information.

If someone can point out what is bad, and how it could be better, this would justify a new ticket.

> The tooltips for the tabs are in static positions, whereas the tooltips for the Download/Play button and the icon-button-things follow the cursor.

Another question @NikolaiResokav: is this a bug we should report to loveframes, or am I using the tooltips incorrectly? (see src/core/ui.lia:57)

> The font used for the description isn't the easiest to read.

Totally legit. #120

> The "Application" button which flips the order of the games is maybe not so useful. Also, when it's pressed, the list is sorted by a different order, with the starting-with-lower-case-name "trAInsported" and the top/bottom.

Has since been fixed.

> Alt-F4 doesn't close the window on Windows.

Totally legit. #121

> Perhaps there could be an indication if a game is new or updated?

Totally legit. #122

> I had an idea for the games list: Instead of having three tabs, maybe there could be one list, with the downloaded games at the top, and the not-downloaded games underneath, and some sort of visual way to tell them apart, and the downloaded games are sorted by time-last-played, which kind of "replace" the concept of favourites. Just an idea! :P
> The games list could use more vertical spaaace.
> In the old Vapor I really liked how you could scroll through the game screenshots quickly and play games with one click.

Already being prepared for in #70

> I've heard talk of supporting older versions of LÖVE, but maybe effort would be better spent creating compatibility layers, conversion scripts and migration guides so that all LÖVE games could benefit from being compatible with the latest version?

Some folks abandon source code, and I don't really want to take it upon our shoulders to be the ones to update this. If anyone feels differently, please open a new issue with this section in the body and a response.

> I don't really think a rating system would be so cool, since... you know... all the games are free, and all it takes to find out if you like a game is to look at the screenshot and download it and see for yourself. And I don't think being at the bottom of the list is going to make the creator feel that great. And it could just result in the lowest common denominator bubbling to the top.

This is a good point, and I will cross post this onto #102

> Too much aspects are discussed at the same time.
> @Yonaba: totally agree, it's a shame it's taken me so long to get to this.
