### ISSUE TITLE
Get Desert Loot into vapor!

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#103]
http://sixpackofseagulls.com/#desert-loot

Contact @GloryFish via twitter

**Comment by GloryFish** [comment]
Hi! is there anything I can/should do to help with this?

**Comment by josefnpat** [comment]
@GloryFish as much as you'd like to!

All I need is your permission, and I will fork and provide merge requests to bring your games to the 0.8.0 API.

If you would like to help, this is what needs to happen;
- Update your love games that you want in vapor to Love 0.8.0
- Ensure your game does not start in fullscreen
- Provide a screenshot of the game 436x245 PNG (Preferably without text!)
- Host the `.love` at some location hosted on http (not https, we have luasocket but no luasec/openSSL)

**Comment by josefnpat** [comment]
For more information, check out the https://github.com/josefnpat/vapor/blob/master/README.md !

**Comment by josefnpat** [comment]
@GloryFish Thanks so much! If you want any other games in vapor, you know the drill!

Thanks!
