### ISSUE TITLE
Get Triad

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#106]
@BlackBulletIV 

http://www.ludumdare.com/compo/ludum-dare-27/?action=preview&uid=3915

**Comment by mebens** [comment]
What information do you need from me?

**Comment by josefnpat** [comment]
@BlackBulletIV Do you mind if we point vapor right at `http://nova-fusion.com/games/triad/triad.love` ?

Otherwise I can just pull the rest of the info from your website page! :)

**Comment by qaisjp** [comment]
Oooh nice game @BlackBulletIV  :)

**Comment by mebens** [comment]
That's the URL for the .love file, so go ahead.

@qaisjp Thanks. :)

**Comment by josefnpat** [comment]
@BlackBulletIV if you have any other love 0.8.0 games, feel free to submit them!
