### ISSUE TITLE
Get Boyfriend Simulator: Feed My Boyfriend

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#107]
@leafo

http://www.ludumdare.com/compo/ludum-dare-27/?action=preview&uid=4321

**Comment by josefnpat** [comment]
@leafo /me makes puppy eyes

**Comment by josefnpat** [comment]
```
13:29 <markgo> josefnpat, you should add leafo boyfriend game
```

**Comment by leafo** [comment]
so I was going to add it but I keep forgetting. You can just do it if you want :+1: 

http://leafo.net/dump/feed_my_boyfriend.love

**Comment by josefnpat** [comment]
<3 on it!

**Comment by josefnpat** [comment]
@leafo details, should be good, but if not, just tell me!
