### ISSUE TITLE
Why not allow games containing binary?

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#108]
and replace it with "Must be compatible with all platforms" and "Games containing binary DLL's cannot be hosted by me"

In the end, the user gets to play the code on all platforms.

**Comment by josefnpat** [comment]
I'm not sure I entirely understand this ticket;

I think a lot of the confusion might be solved by finding a better word for binary, and providing more examples. I'm thinking;

> Your game must not:
> - use compiled Lua libraries not provided by love (e.g. luasec, enet, lsqlite3, LuaFileSystem).

Or are you saying that we ought to allow folks to use compiled Lua libraries?

**Comment by qaisjp** [comment]
Yes, that. I don't know how I structured this issue.

**Comment by josefnpat** [comment]
Yes to what? The prior (update description) or the latter (allow bin libs)?

**Comment by qaisjp** [comment]
Allow compiled Lua libraries not provided by love

**Comment by qaisjp** [comment]
I think we misinterpreted my issue, my point was that why don't you allow compiled .so/.dlls? There's no harm done.

**Comment by josefnpat** [comment]
@qaisjp I see.

Making cross-platform bin's is very tricky to do it right, especially for linux.

Unless someone can come forward and provide a straightforward way that we can validate that the .dll's/.so's will work on all platforms (win,osx,lin) it's better to make it a steadfast rule, and let those who are more knowledgeable argue this point.

**Comment by qaisjp** [comment]
fair
