### ISSUE TITLE
SHA1's do not validate properly on 32bit

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#109]
This bug was introduced between 0.2.2 and now.

It might have been improperly used in vapor when we updated @Boolsheet's hashing library.

See 18f19b9c30988129c8be8ffb5e61719945ed92c4 and #95 

Thank you Razzeeyy for pointing this out.

This bug does not effect the 0.2.2 tag.

**Comment by qaisjp** [comment]
did you rehash all the loves again? there may be a very small possibility of inconsistency.

**Comment by josefnpat** [comment]
@qaisjp I don't believe so, because the 0.2.2 release still works.

**Comment by josefnpat** [comment]
This still hashes properly on my desktop at home (x86_64) but not on my machine at work (x86). There might be a 32/64 bit conversion issue in the hashing library.

**Comment by josefnpat** [comment]
Just booted up a virtualbox with 32-bit of Ubuntu, I can confirm that it works on 64bit and not 32bit.

There's not much new on the tip that warrants a new release, so I think I will wait for @Boolsheet to get back to me on the hashing library, and we will see if we can get a patch, new version of the hashing library or just use the older version that is in 0.2.2 .

**Comment by josefnpat** [comment]
Thanks @boolsheet! Updating the `bit.lua` fixed it!
