### ISSUE TITLE
Submitting PacPac

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#115]
Hi,

This implementation of [Pacman](https://github.com/tylerneylon/pacpac) is absolutely gorgeous. And it should be featured in Vapor. IMO.
Contact @tylerneylon

Regards,
Roland.

**Comment by josefnpat** [comment]
Thanks @Yonaba ! I have contacted @tylerneylon.

**Comment by tylerneylon** [comment]
Thanks for mentioning this idea! I'm happy to submit PacPac, but I'm superbusy with some work and can't do it immediately. Hopefully within the next few days. Vapor looks cool.

**Comment by josefnpat** [comment]
@ tylerneylon Thanks for the quick reply! If you don't have time in a few days, I'm happy to help :)

**Comment by josefnpat** [comment]
@tylerneylon Thanks!
