### ISSUE TITLE
filter on controller support + controller support for vapor

### ISSUE THREAD

**Issue by jadebrew** [josefnpat/vapor#131]
le title.

**Comment by josefnpat** [comment]
This might be nice to have a flag for each game object for games that support controlelrs.

We would need to test the games a little more extensively that do claim to have controller support.

We would also have to test against a preset controller set, e.g. xbox 360, PS3, etc.

**Comment by josefnpat** [comment]
It might also be nice to have vapor react to controller input.

Could use https://github.com/josefnpat/dong

**Comment by josefnpat** [comment]
This might be something nice to have on vapor1.x

**Comment by pablomayobre** [comment]
Well it should probably be part of `vapor-ui` and seeing how you closed most issues related to that stuff, I think maybe this should be closed too
