### ISSUE TITLE
Linux LoveFrames column-list doesn't work until you select a tab

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#134]
Is anyone else experiencing issues selecting a game right when vapor starts?

I can select a game after selecting one of the tabs.

I just ran this Ubuntu 12.04 on a VM, and the same issue exists.

Not much has changed list wise for vapor's implementation of the ColumnList, it makes me think that maybe there's an bug with the new 0.9.6.4 Alpha of LoveFrames?

I just changed the theme to the default "Blue" and the bug still persists, so that rules out Unek's loveframes-gray-theme codebase.

Before I file a bug against LoveFrames, I plan on recreating the issue somehow. I tried the LoveFrames-Demo, and there doesn't seem to be an issue with the ColumnList there.

It's hard to tell, but this needs to be investigated.

**Comment by NightKawata** [comment]
I don't think that's an OS-related issue. (It also happens on Windows (I run 7))

**Comment by Yonaba** [comment]
I encountered that issue. It is related to LoveFrames latest 0.6.9.4.
When cloning the repo Vapor, then running the setup.sh script, you will get the bug. If you replace the folder src/lib/lf with an earlier version, everything is okay. :)

**Comment by KennyShields** [comment]
Just pushed a commit that should fix this issue: https://github.com/NikolaiResokav/LoveFrames/commit/9aaf07f66ff6ca74dbf709b65ea748246dfd0364

**Comment by josefnpat** [comment]
Good find @Yonaba !

Thanks @NikolaiResokav  for the fix!
