### ISSUE TITLE
Submitting GrandHealthAuto

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#140]
I loved playing [this](https://github.com/GrandHealthAuto/game), it should be in Vapor.
What do you think ?

Author is @GrandHealthAuto :)

Regards,
Roland.

**Comment by josefnpat** [comment]
Oooo, good find. This was done for one of the jam's by @vrld @martinfelis and others.

https://github.com/GrandHealthAuto/game/issues/2

**Comment by ppetermann** [comment]
what information do you need?

**Comment by Yonaba** [comment]
All of [these](https://github.com/josefnpat/vapor#how-can-i-add-my-game), please :)
There are [criteria](https://github.com/josefnpat/vapor#game-criteria), but last time I checked, it seems GHA already meet them. :+1:

**Comment by ppetermann** [comment]
https://github.com/GrandHealthAuto/game/issues/2 <-- i was kinda trying to pull the busy card here

**Comment by josefnpat** [comment]
Thanks guys!

**Comment by josefnpat** [comment]
Bump :horse:

**Comment by martinfelis** [comment]
Just sent a pull request. Hope it works.

**Comment by josefnpat** [comment]
Thanks!
