### ISSUE TITLE
Submitting Revenge Of Olmec

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#141]
Hi,

A [tank game](https://github.com/bobsomers/remote-game-jam-v2), playable and quite well polished,
Author is @bobsomers.

Regards,
Roland.

**Comment by josefnpat** [comment]
This seems like a great game!

From the commits, the github authors are:

@bobsomers
@Ubersmake
@Trayus

They don't have an open issue system, so hopefully they will see this ping. I don't see a license in the repo, so this may prove to be fruitless if they never respond.

If you guys are interested in having this game in  [Vapor](https://github.com/josefnpat/vapor) please respond in this ticket, or tell us how to contact you!

**Comment by josefnpat** [comment]
<blockquote class="twitter-tweet" lang="en"><p><a href="https://twitter.com/bobsomers">@bobsomers</a> Hey, we&#39;d like to get one one your games in Vapor!&#10;&#10;<a href="https://t.co/y8XWQU22OY">https://t.co/y8XWQU22OY</a>&#10;&#10;<a href="https://twitter.com/search?q=%23L%C3%96VE&amp;src=hash">#LÖVE</a> <a href="https://twitter.com/search?q=%23love2d&amp;src=hash">#love2d</a></p>&mdash; Seppi ҉ (@josefnpat) <a href="https://twitter.com/josefnpat/statuses/406855964185206785">November 30, 2013</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by bobsomers** [comment]
Hey guys. Let me contact the people involved in making it and see if I can get their permission to release it under a permissive license. I doubt there will be any problems.

**Comment by josefnpat** [comment]
@bobsomers Thanks!

**Comment by bobsomers** [comment]
Sorry, I forgot to get back to you. I've gotten permission from everyone involved so you are good to go.

**Comment by josefnpat** [comment]
@bobsomers Thanks so much!

I'm back from vacation, so I can start dealing with things again!
