### ISSUE TITLE
Submitting Meteor Defense

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#143]
Hi,

A [nice game](https://github.com/jotson/1gam-jan2013), where you defend a town against falling meteors. [In-game gameplay video](https://www.youtube.com/watch?v=3mOqFVJPNtE) is available.
Author is @jotson

Regards,
Roland.

**Comment by josefnpat** [comment]
Repo is here: https://github.com/jotson/1gam-feb2013

**Comment by josefnpat** [comment]
https://github.com/jotson/1gam-feb2013/issues/1

**Comment by josefnpat** [comment]
We have permission to use his games in vapor.

https://github.com/jotson/1gam-feb2013/issues/1#issuecomment-29653535

**Comment by josefnpat** [comment]
f9db1f826b3a89d368338bf101e5e0eb7696f8e9
