### ISSUE TITLE
Submitting Eins Eins Funf

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#144]
Hi,

This [game](https://github.com/jotson/1gam-jan2013) is all about fuel. And I loved it.
[In-game video](https://plus.google.com/photos/105783622938386957806/albums/5829323380128334929/5835277748884803986) is available. 
Author is @jotson

Regards,
Roland.

**Comment by josefnpat** [comment]
https://github.com/jotson/1gam-jan2013/issues/1

**Comment by josefnpat** [comment]
We have permission to use his games in vapor.

https://github.com/jotson/1gam-feb2013/issues/1#issuecomment-29653535

**Comment by josefnpat** [comment]
3c6d5f040e95f318ed41415183809f8060be882b
