### ISSUE TITLE
During execution, downloaded games aren't added to downloads.

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#147]
It seems that we need to fire a trigger to update the downloads section when a game finishes downloading.

It doesn't seem to work.

ArchLinux, LuaJIT w/ Love 0.8.0

**Comment by jadebrew** [comment]
yeah for me the same, on two computers; the downloads section seems to be updated after running a game, starting the application again, but not after downloading a game.

both Windows 7, Love 0.8.0.
