### ISSUE TITLE
Trying to add Possession to Vapor

### ISSUE THREAD

**Issue by vaughantay** [josefnpat/vapor#150]
{
      "id":"possession",
      "name":"Possession: Escape from the Nether Regions",
      "sources":{
        "1386085761":"http://taylor-vaughan.com/possession/possession.love"
      },
      "hashes":{
        "1386085761":"e359a2996cc3e9a5e9cd41da30c96f0954e82810"
      },
      "stable":"1386085761",
      "author":"Taylor Vaughan",
      "website":"http://taylor-vaughan.com/",
      "description":"A roguelike made for the 2013 7-Day Roguelike Challenge. You play as a weak ghost who has only one power: the ability to take control of the bodies of other monsters!",
      "engine":"love-0.8.0",
      "image":"http://taylor-vaughan.com/possession/screenshot.png"
    }

**Comment by josefnpat** [comment]
I have;
- added the sizes array along with the size of the .love
- corrected the invalid sha1sum hash.
- Shortened the name (space issues, may be able to revert when #70 comes maybe?), and put the rest in the description.

Push incoming!
