### ISSUE TITLE
Abstract GUI

### ISSUE THREAD

**Issue by jadebrew** [josefnpat/vapor#152]
Dear Seppi,

Although you're here on the couch I wanted to tell you on github as well, because you're too much intoxicated by alcohol anyways to remember this if I tell you in person that I'd love to have an abstract version of the GUI so that people can make custom gui versions that can be chosen from settings menu.

If that would be possible, that'd be great, yeahhhh.

bye.

xxx

**Comment by josefnpat** [comment]
Thanks you

**Comment by josefnpat** [comment]
Closing this ticket since this is a part of the vapor1.x outline
