### ISSUE TITLE
Make website more attractive

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#153]
The website is very informative, but rather blank. http://vapor.love2d.org/

It might be nice to create some theme that mathces the logo @riidom made for the project.

**Comment by Yonaba** [comment]
I'll vote for something similar to what [Santos](http://santos.nfshost.com/lovepowered.html) did.

**Comment by riidom** [comment]
If you need similar graphics that fit the logo, I should be able to get something done. I have zero experience in webdesign, I'd need precise specs, or some kind of mockup where I can orientate along the placeholders.

**Comment by josefnpat** [comment]
From @riidom : http://pastebin.com/zpcGSPP5

**Comment by josefnpat** [comment]
@Yonaba I agree. What he posted on the forums was very nice!

![](http://i.imgur.com/rGJ6ysF.png)

**Comment by riidom** [comment]
Color palette pipetted from the logo:

```
84c2ed blue
a2c5f1 blue highlight
ed8484 red
fe9daa red highlight
fa836d red reflection (bit darker than basic red)
5a5a5a steel
7a7a7a steel reflection (brighter)
5a4e3e copper
e49455 copper reflection on steel (if you need some orange)
```

![Screenshot](http://i.imgur.com/tZ2KNOh.png)

**Comment by josefnpat** [comment]
@riidom Thanks!
