### ISSUE TITLE
Vendor

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#16]
For some better structure of third-party libraries and content and to sort out proper licensing, I think a vendor folder would be appropriate.

For example:

src/vendor/json/json.lua
src/vendor/json/LICENSE

src/vendor/famfamfam/....png
src/vendor/famfamfam/LICENSE

src/vendor/middleclass/middleclass.lua
src/vendor/middleclass/LICENSE

or something like that

**Comment by josefnpat** [comment]
22:53 <leafo> also you should store files in different directories, so someone doesn't name their screenshot games.json and break everything

**Comment by josefnpat** [comment]
Please con't close tickets unless the fix is in upstream.
