### ISSUE TITLE
ADD LANG (danish)

### ISSUE THREAD

**Issue by ghost** [josefnpat/vapor#161]
da.lua:

return {

  --Translation by Gustav Geisler (jjmafiae)
  -- Internal

  id = "DA",
  name = "Danish",

  -- Tabs

  list_all = "Alle",
  list_all_tooltip = "Alle spil (%d)",
  list_favorite = "Favoritter",
  list_favorite_tooltip = "Dine favorit spil",
  list_downloaded = "Downloadede",
  list_downloaded_tooltip = "Downloadede spil",
  list_new = "Nye",
  list_new_tooltip = "Nyeligt insættede spil (%d)",

  -- Global Buttons

  settings = "Indstillinger",
  settings_tooltip = "Indstil Vapor",

  -- Info Section

  size = "Størrelse",
  welcome = "Velkommen til Vapor.",
  nodescription = "Intet resumé tilgængeligt",

  -- Info Button Status

  download = "Download",
  download_tooltip = "Download dette spil nu.",
  downloading = "Downloader ...",
  downloading_tooltip = "Dit spil bliver downloadet",
  hashing = "Tjekker ...",
  hashing_tooltip = "Dit spil bliver tjekket.",
  invalid = "Fejl",
  invalid_tooltip = "Der er sket en fejl. Klik for at slette spil.",
  play = "Spil",
  play_tooltip = "Dette spil er klar til at blive spillet",

  -- Game Buttons

  favorite_tooltip = "Put det her spil på dine favoritter.",
  delete_tooltip = "Slet det her spil.",
  website_tooltip = "Besøg udviklerens hjemmeside."

}

**Comment by josefnpat** [comment]
Good idea to add a maintainer info. :+1:
