### ISSUE TITLE
Automatically updating vapor

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#17]
Automatically updating vapor on run
http://www.love2d.org/wiki/LoveUpdate is in the public domain and code can be based on this!

**Comment by josefnpat** [comment]
Ensayia keeps begging for this

**Comment by josefnpat** [comment]
From #love, 

people are suggesting we make a .love that downloads and updates vapor.

http://i.imgur.com/hmWS4Ex.jpg

**Comment by qaisjp** [comment]
Epic meme. "LOVE updater" would be a bit excessive perhaps, I like just maintaining and running one single file. It shouldn't be too hard to maintain a separate branch/repo which works as a submodule for this repo. Basically src/updater/main.lua. vapor.love would then just execute "updater" folder in love (just like running a game within vapor except vapor closes)
