### ISSUE TITLE
Ability to create link on Desktop

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#18]
Vapor can create a link to the game on the desktop, including a new icon if it exists in the catalogue file (catalogue file:games.json)

**Comment by josefnpat** [comment]
I'm not sure if we want this application doing this by default, but if we did do this;
- Would need to be crossplatform (need docs on creating win, osx and linux icons)
- Would need to be able to turn this on/off
- Each game would need a `.ico` file.

**Comment by qaisjp** [comment]
Yeah, I don't think doing this by default is a good idea. When games have individual pages you can choose "Create shortcut on desktop"
For Windows, shortcuts have .uri extensions. You can generate a shell script for osx and linux.
