### ISSUE TITLE
Get the old Vapor ready for the upcoming LD

### ISSUE THREAD

**Issue by Bobbyjoness** [josefnpat/vapor#196]
We should spruce up the old Vapor client and give it one last update before we retire it. We can use the LD as publicity to get us a whole lot of submissions and eyes on Vapor but we need to have it ready soon. I'm currently working on refurbishing Vapor on my own fork. I'm working on the addCompat branch. Its almost ready to be used. Maybe we can give a new GUI while we are at it.

**Comment by josefnpat** [comment]
We need to finish and test the compatibility layer before we update the UI, imo!

Features are way more important if you ask me.

If you do any UI changes, be sure to have them in a different branch, as there's QA for that as well!

**Comment by Bobbyjoness** [comment]
The compat will be ready for the next LudumDare. Currently it is acceptable but not as good as can be. So all that is left is testing and code review/clean-up. The branch is here https://github.com/Bobbyjoness/vapor/tree/addCompat please test.

**Comment by josefnpat** [comment]
This ticket is obviously very old and should be closed, lol
