### ISSUE TITLE
cure/async.lua:108: Failed to resume coroutine: already connected.

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#23]
This error has happened to three individual users, but interestingly 2/3 instances has been on a OS X.

```
 cure/async.lua:108: Failed to resume coroutine: already connected.
```

http://i.imgur.com/4lOa4zt.png
http://i.imgur.com/leYLhr7.jpg

see;
- http://love2d.org/forums/viewtopic.php?f=5&p=115456#p115405
- http://love2d.org/forums/viewtopic.php?f=5&p=115456#p115432

@leafo

I'm not sure how the code works, but I'm happy to dig through it. Any ideas?

**Comment by qaisjp** [comment]
*core

**Comment by josefnpat** [comment]
Thanks leafo! 9cdc65335838b8312d45a0ab4cdd8725759a9871

Lafolie confirms!
