### ISSUE TITLE
Progress bar and hover text whilst downloading

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#26]
Underneath the text saying the game, a green progress bar will be shown showing the time left to complete the download. Hovering on the row will show "xx/unit / xx/unit" or "52%" (xx/unit can be 250kb/30mb depending on the amount or just stick to kb's)

I'd like to assign this to myself.

**Comment by josefnpat** [comment]
Sounds good, make it happen!

There should be a way to determine how much of the data has been downloaded via the sink (I think? This is mostly @leafo 's realm at this point, as he wrote the async.)

Check out these docs, might help you get started;

http://w3.impa.br/~diego/software/luasocket/old/luasocket-2.0-beta2/ltn12.html

**Comment by leafo** [comment]
This one is a bit tricky.

This is the function that luasocket uses to move data from source to sink when downloading a file that it knows the size of:
https://github.com/diegonehab/luasocket/blob/master/src/socket.lua#L109

You'll see it uses a length variable to keep track of how much is left, that's the value we need. I'm thinking we replace this function with out own implementation that exposes that information.

This is where it is invoked: https://github.com/diegonehab/luasocket/blob/master/src/http.lua#L169

If you don't want to do it I don't mind giving it a shot.

**Comment by josefnpat** [comment]
@leafo cheers!

@qaisjp still up for the task?

**Comment by qaisjp** [comment]
leafo, go ahead with it if you want. Right now it's sort of a chase to get features and I can't code now so, you know more about sockets and async.lua anyway so yeah @leafo you can give it a shot :smile:

**Comment by josefnpat** [comment]
@leafo This isn't a priority at all, so if you have other stuff, don't worry too much about this :) Thank you for the async and support fixes :)

**Comment by josefnpat** [comment]
Until I update the UI, I figure I might do this as a cop out until we can put more research into this.

0% disabled .. not downloaded
33% enabled .. downloading
66% enabled .. hashing
100% disabled .. downloaded

**Comment by josefnpat** [comment]
https://github.com/NikolaiResokav/LoveFrames/issues/90#issuecomment-29173230

**Comment by josefnpat** [comment]
https://love2d.org/forums/viewtopic.php?f=5&t=76576
