### ISSUE TITLE
main.lua:207: attempt to index field 'games' (a nil value)

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#27]
This screenshot -> http://cl.ly/QeKt <- shows an error and traceback immediately whilst running the src folder (drag and drop over love.app). 

This is the tree I used [latest as of now]: https://github.com/josefnpat/vapor/tree/5ab67fdccda2f26ea89f5a9c94aa1eb12437b98b

**Comment by josefnpat** [comment]
Can you post the `settings.json` file here, delete it, and run vapor again?

I've seen this issue, and it's a `settings.json` api mismatch.

We ought to add some checks to the system to make sure the settings file is properly structured. If not, we should bomb the current version.

**Comment by josefnpat** [comment]
in the newest build, you should be able to use `love vapor_<hash>.love clearcache` if you like.

**Comment by qaisjp** [comment]
Deleting settings.json (in that tree, i haven't updated yet) fixed the issue. Then I got the coroutine error too!

**Comment by josefnpat** [comment]
Can you recreate the `settings.json` error so we have a working test case to work with?

**Comment by qaisjp** [comment]
Sorry I did keep the settings.json in a gist, forgot to post it here. Created 6 hours ago: https://gist.github.com/qaisjp/8251be11254c3689068f

**Comment by josefnpat** [comment]
This got fixed, incidentally, due to 5c797229.
