### ISSUE TITLE
Pagination or infinite scrolling

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#28]
I think we should use infinite scrolling because then items on other pages won't be noticed (if it's not on the first page, it doesn't exist! - Google).
Needed because the screen doesn't fit!
http://cl.ly/QeKt

Child of #10, and #13

**Comment by josefnpat** [comment]
What do you mean by infinite scrolling, like reddit / twitter?

I don't understand how infinite scrolling solves this problem?

At some point we're going to have too many games, and we will need pagination / scrollbar, but that relates to #3, #11, #13, #14 

We're quickly approaching that bridge, surprisingly!

**Comment by qaisjp** [comment]
Infinite scrolling is where the next list of games are "downloaded and listed" (games dont download, just the meta info is) when the scroll reaches the bottom. This would only apply to massive catalogues in the future. Right now Vapor doesn't fit on my screen so scrolling would just apply for now, and then later implement infinite scrolling.
