### ISSUE TITLE
Sorting Games

### ISSUE THREAD

**Issue by zer0problem** [josefnpat/vapor#3]
The ability to sort games by Name,Author and Download status.

**Comment by josefnpat** [comment]
I just committed 73798fce5e193fe5f93cf3651c5545fdb92e5e59 which should sort the games by name.

What's the best way to implement this you think? `s` for sort, and it toggles between the three states?

**Comment by qaisjp** [comment]
headers that can be clicked would be more informative and less remembery

**Comment by josefnpat** [comment]
Should seriously consider rewriting the display part to use LoveFrames.

**Comment by qaisjp** [comment]
:+1:

**Comment by josefnpat** [comment]
This is just an old ticket :)
