### ISSUE TITLE
run.sh attempts to zip MY HOME FOLDER?!

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#32]
https://gist.github.com/qaisjp/085017db53277744658e
this happens when i attempt to open run.sh in terminal ( http://cl.ly/QdkH )
where does this zip to so i can delete the zip file, if it exists?

**Comment by josefnpat** [comment]
You need to `cd /Users/qaisjp/Dropbox/Projects/vapor/` then `./run.sh`

Then it will attempt to zip the correct folder.

Also, you need to install `git` and `love` in your command line if you want this to work.

This script is meant as a debugging tool to test the git information within a build before actually using the `build.sh` (which will build the windows 32, windows 64, OS X and love build of the game.)
