### ISSUE TITLE
No mechanism for ensuring love archives are valid

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#35]
Steps to reproduce;
- Spam click on a bunch of games to download
- Close vapor before they finish downloading
- Start vapor, and attempt to start a game
- See the rubber piggy because the zip is an invalid archive.

Current workaround;
- Use `delete` or `backspace` key to delete the game
- Click to re-download the game.

Suggested fix;

Unless we can think of a `CheckZip()` function like DotNet's that is cross platform, I say we start passing out the MD5 (preferably SHA256/512) in the `games.json`, and using a pure Lua implementation of one of these. We would only have to check the game archive's integrity on start of the game.

We could also use a "broken" icon for the game, and when they click on it, it would re-download the game.

On a technical side, this would also ensure that developers don't change the hosted .love file without our knowledge (thus forcing usage of the sources array in each game.)

**Comment by josefnpat** [comment]
http://regex.info/blog/lua/sha1

**Comment by SiENcE** [comment]
I suggest sha256. But we have to make sure, the distributed games.json is not compromised.

**Comment by josefnpat** [comment]
@SiENcE 
I can't seem to find SHA256 in pure lua

I found SHA-1(160 instead of 256) in pure Lua 5.1 (http://regex.info/blog/lua/sha1) 

This seems like the best option at the moment. I have a working patchset for this, and will push once I finish the documentation. If you can find something better, I can use that, but it may force users to redownload games.

**Comment by josefnpat** [comment]
I have increased the speed of this from 2MiB/s to 15MiB/s. Thanks @Ensayia and @boolsheet.

@SiENcE 

If you can give a good reason why we should ditch SHA1 (for our usage) we can now use (via bslf and it's hash implementations);
- CRC32
- MD5
- SHA1
- SHA256
