### ISSUE TITLE
Use RELEASES

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#40]
I noticed that on the forum post (which I'm not really contributing to much) you put an update. Instead of zipping the src folder and then uploading it to forums, use: https://github.com/josefnpat/vapor/releases

**Comment by josefnpat** [comment]
I'll buy that for a dollar. Thanks.

**Comment by josefnpat** [comment]
" Attach binaries for this release by dropping them here." HNNNNG, BUT I DON'T WANT TO START UP NAUTILUS.

**Comment by qaisjp** [comment]
Binaries can be .love's :)

**Comment by josefnpat** [comment]
There's no browse button for me to upload them with. I have to start up a file manager to drag and drop them. To do that, I have to start nautilus.

**Comment by qaisjp** [comment]
ohhhh
