### ISSUE TITLE
level system.

### ISSUE THREAD

**Issue by ghost** [josefnpat/vapor#43]
could you make a level system were you get XP for each download?

**Comment by qaisjp** [comment]
It's an app launcher, not a game. vapor shouldn't  give rewards for downloads. So probably no.

**Comment by qaisjp** [comment]
#44

**Comment by josefnpat** [comment]
@qaisjp I think @RadioActiveGears is looking for something similar to what steam does.

It isn't a bad idea in theory, but practically impossible in practice for us.

We would have to binary everything we distribute to prevent folks from cheating, and then we'd have to figure out how to encrypt it from even the user using the software.

If we don't care that some folks are gonna hack it, it might be nice, but this needs to wait for the luasec module to come in so we can do proper authentication.

**Comment by ghost** [comment]
why not let people cheat?

**Comment by qaisjp** [comment]
josefnpat means cheating the system not the actual implemented cheats

**Comment by ghost** [comment]
i know.

**Comment by qaisjp** [comment]
Anyway please explain this feature more :smile:
