### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#44]
Statistics would be cool but unneeded.

**Comment by josefnpat** [comment]
http://stackoverflow.com/questions/6198194/how-to-see-count-of-project-downloads-on-github

Looks like it was "depreciated" with downloads. Now releases doesn't have it;

I have a working download count running on my drupal instance on missingsentinelsoftware.com

I might make a website as a sub page of it, and use that.

**Comment by qaisjp** [comment]
I was talking about stats for vapor itself, like "Number of games played, number of downloads made, etc" but OK then

**Comment by josefnpat** [comment]
I see.

I'm keeping tabs on my download count ;) WHO ISN'T?

But seriously, we can add triggers so we can get "trending" and "top downloaded" etc. Seems easy to fake though.

**Comment by josefnpat** [comment]
We have download counts on the community site now!

**Comment by qaisjp** [comment]
Yay!
