### ISSUE TITLE
Flicker of image when mouse is moving between items

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#48]
Introduced in #47 due to Love Frames.
Love Frames' mouse bounding box function is exclusive of borders which means that when the mouse lies on the intersection between two elements (in our case, two panels; every row is a panel) no item is selected. This is where the issue lies.

**Comment by josefnpat** [comment]
Please con't close tickets until they are closed in the mainline.

**Comment by josefnpat** [comment]
This pull request was not merged.
