### ISSUE TITLE
Hawthorne

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#51]
We should see if there is a release of community Hawthorne journey

**Comment by qaisjp** [comment]
You mean Journey to the Centre of Hawkthorne? https://github.com/hawkthorne/hawkthorne-journey/releases

**Comment by josefnpat** [comment]
Yeah, I'll open a ticket in their tracker.

**Comment by josefnpat** [comment]
https://github.com/hawkthorne/hawkthorne-journey/issues/1687
