### ISSUE TITLE
Deleting app whilst downloading.

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#52]
```
downloading mari0.png
mari0-1375538536.love is hashing.
Error: core/async.lua:115: Failed to resume coroutine: core/async.lua:185: Could not open file mari0-1375538536.love. Does not exist.
stack traceback:
        [C]: in function 'read'
        core/async.lua:185: in function 'snk'
        [string "ltn12.lua"]:275: in function 'step'
        [string "ltn12.lua"]:285: in function 'all'
        [string "http.lua"]:167: in function 'receivebody'
        [string "http.lua"]:323: in function <[string "http.lua"]:290>
        (tail call): ?
        core/async.lua:80: in function <core/async.lua:79>
stack traceback:
        [C]: in function 'error'
        core/async.lua:115: in function 'update'
        events/init.lua:94: in function 'update'
        [string "boot.lua"]:407: in function <[string "boot.lua"]:373>
        [C]: in function 'xpcall'
```

This is caused by pressing backspace whilst downloading an app

**Comment by qaisjp** [comment]
@leafo async.lua

**Comment by leafo** [comment]
To cancel a download you would just need to remove the associated coroutine from the instance of SocketQueue. You could modify the `request` method to return the coroutine it creates for that request. Then add a method, `cancel_request`, that would take a coroutine and remove it from the coroutines instance variable.

**Comment by josefnpat** [comment]
I don't think we need to introduce a cancel just yet (unless you think it's an easy fix, @leafo)

Let's keep this ticket open as an enhancement.

**Comment by qaisjp** [comment]
It's a bug too

**Comment by qaisjp** [comment]
Oh you fixed it ^.^ ill try and add this fix to my fork later if needed.

**Comment by josefnpat** [comment]
This got fixed a while back, sweet.

Opening a new ticket for the enhancement. #123
