### ISSUE TITLE
A couple of logos that I made.

### ISSUE THREAD

**Issue by icrawler** [josefnpat/vapor#53]
:3

![vapor-logo-v2](https://f.cloud.github.com/assets/2682900/929523/05c58416-ffe8-11e2-8572-c340ae0bc063.png)
![vapor-logo-v2-inv](https://f.cloud.github.com/assets/2682900/929524/05d66ba0-ffe8-11e2-8c2b-f28b614daf58.png)

**Comment by qaisjp** [comment]
nice :+1:

**Comment by josefnpat** [comment]
@icrawler This is a big jump from the ones you posted on the forums.

I love this logo, and am very close to slapping it on everything.

I love how it feels like the steam gear, so it will get the point across really well.

If you have time, would you be able to do a bit of experimentation with these ideas?

Consider working in the duality of the moon and earth, much like the Lua logo; http://i.imgur.com/aKrQu6F.png At the moment I get the feeling of "olives"

Consider working in the color scheme of love's logos into the logo;https://www.love2d.org/wiki/L%C3%B6ve_Logo_Graphics

Also, are these vector files?

**Comment by qaisjp** [comment]
Vector would be important.

**Comment by icrawler** [comment]
I have the Adobe Illustrator project files, although I can export these as SVG as well.

As for the color scheme, the Vapor program thingy is pretty much black-and-white soo...

Edit: Just incase you want to know which font I used, it's the Futura font.

**Comment by josefnpat** [comment]
https://love2d.org/forums/viewtopic.php?f=5&t=40743&p=120862#p118869
