### ISSUE TITLE
Get Warp-Run into vapor

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#54]
https://bitbucket.org/aaron_wizardstar/warp-run

I have pm'd AaronWizard. We'll wait a few days for his response, and then check the license of the game.

**Comment by qaisjp** [comment]
His license shouldn't matter since it not part of the codebase. Rights to use it may be required though.

**Comment by josefnpat** [comment]
"Sure.  :)" AaronWizard  via love2d.org/forums
