### ISSUE TITLE
Get In Your Face City Trains into vapor

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#59]
https://www.love2d.org/wiki/In_Your_Face_City_Trains

While it is 0.7.2, I believe there have been some ports to 0.8.0.

If not, it can't be that hard to port it to 0.8.0.

This is truly a classic.

**Comment by qaisjp** [comment]
Or we can implement old version loading...

**Comment by josefnpat** [comment]
<blockquote class="twitter-tweet"><p><a href="https://twitter.com/josefnpat">@josefnpat</a> I&#39;d like to update it for 0.8.0 first. I&#39;ll get back to you when I have. :)</p>&mdash; Simon Larsen (@SimonLarsen) <a href="https://twitter.com/SimonLarsen/statuses/376741988973826048">September 8, 2013</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by josefnpat** [comment]
Woo hoo!

<blockquote class="twitter-tweet"><p><a href="https://twitter.com/josefnpat">@josefnpat</a> Fixed the errors I could find yesterday, so you&#39;re free to add it now. :) <a href="https://t.co/PWMXQBVWQr">https://t.co/PWMXQBVWQr</a></p>&mdash; Simon Larsen (@SimonLarsen) <a href="https://twitter.com/SimonLarsen/statuses/377119437813329920">September 9, 2013</a></blockquote>

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by josefnpat** [comment]
Tell me if these details are ok for you, @simonlarsen !

**Comment by SimonLarsen** [comment]
Lukas didn't actually have anything to do with IYFCT so I think

```
"author": "Simon Larsen",
"website": "http://simonlarsen.github.io/",
```

is more appropriate. Otherwise it's good. :)

**Comment by josefnpat** [comment]
@SimonLarsen Should be fixed!
