### ISSUE TITLE
Get Deerhunter into vapor

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#64]
https://love2d.org/forums/viewtopic.php?t=9401

I've contacted him, but he hasn't responded. Ought to check into the license.

**Comment by josefnpat** [comment]
Contacted again via e-mail on website.

**Comment by josefnpat** [comment]
Hi,

About to move to a house with little/no internet but I'll definitely look into it once I have some free time again :)

/Lewis

On 07/09/2013 21:32, Seppi wrote:
Hey,

I'm from the love forums and have been working on Vapor, and was wondering if you would like to include DeerHunter1066 in Vapor, or any other love games?

https://github.com/josefnpat/vapor

https://github.com/josefnpat/vapor/issues/64

-Seppi

**Comment by obscureworlds** [comment]
Did have a go tonight, ugh sorry about the wait am poor as piss at the moment so time for these kinds of things is rare. Basically discovered I am allergic to github and stuck into my own systems that the whole thing kinda blew my mind, tried hacking at the files and forcing it to use a modified games.json only to get a few errors with my server choice.

My addition was

{
      "id":"DeerHunter_ten_sixty_six",
      "stable":"1394839800",
      "sizes":{
        "1398883865":2983110
      },
      "engine":"love-0.8.0",
      "hashes":{
        "1398883865":"4ea497f53baed6fd004a7268b11a8a61a96230a9"
      },
      "image":"nowbrokenlinktomysite",
      "author":"Obscure Worlds Games",
      "website":"http://obscureworlds.co.uk/",
      "sources":{
        "1398883865":"nowbrokenlinktomysite"
      },
      "name":"DeerHunter1066",
      "description":"Arcade shooter where you massacre waves of deer in a forest."
}

was having all kinds of strange stuff from it, including server issues with my weird website... haha your welcome to have a crack yourself if this project isn't dead.

**Comment by josefnpat** [comment]
@obscureworlds what are you trying to link it to? As stated in the project readme, it needs to be on an http, not an https server.

**Comment by obscureworlds** [comment]
was my http server, think its just a problem with my scatty server to be honest

**Comment by josefnpat** [comment]
if you can provide a link, I'd be happy to host it for you.

**Comment by obscureworlds** [comment]
Just emailed it to you :)

**Comment by josefnpat** [comment]
Thanks! Will deal with this as soon as I have time!

**Comment by josefnpat** [comment]
http://vapor.love2d.org/content/deerhunter1066
