### ISSUE TITLE
Get Idiot: Puzzles into vapor

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#65]
https://love2d.org/forums/viewtopic.php?f=5&t=39693

**Comment by Qcode** [comment]
So here's the updated JSON file on Github: https://github.com/Qcode/vapor/blob/master/src/games.json
It needs the source filled in with the idiot: puzzles file still.
The source file for you to host is here: https://dl.dropboxusercontent.com/u/80409786/Idiot%20Puzzles.love

Thanks again for letting Idiot: Puzzles on Vapor, I hope I'm not being too much of a burden here.

**Comment by josefnpat** [comment]
@Qcode Any chance we can update the screenshot to not include the text? The game title will always prominently display the game title.

**Comment by Qcode** [comment]
Alright, I've added a different screenshot to my fork of the games.json file.

**Comment by josefnpat** [comment]
@Qcode all set!
