### ISSUE TITLE
Add websites for game developers

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#69]
Let's get some clickage going for our devs!

Let's add websites to the `games.json` and render it in the client, so folks can clicky click.

Maybe even add twitter, facebook or something? Those would be easy to embed...

http://ananasblau.com/post/49239876807/lua-love-code-to-open-urls-cross-plattform

**Comment by icrawler** [comment]
I'm not sure how will Love2D open hyperlinks though. Perhaps a little edit to the love2d source files will work?

**Comment by josefnpat** [comment]
@icrawler we could use a link icon, and then use the Lua that I posted

**Comment by qaisjp** [comment]
In vapor, awesomium.
otherwise opening in browser should be pretty easy using  OS.execute or similar.

**Comment by josefnpat** [comment]
This functionality has been added. Need to go through the `games.json` with whatever websites we can find.
