### ISSUE TITLE
Create a platform for games.json submission.

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#7]
Should probably use drupal for this ;)

**Comment by qaisjp** [comment]
Isn't drupal a fully fledged CMS? Why not just code something simple and quick using Python or PHP? You could even use the GitHub api to live sync it to the repo.

**Comment by josefnpat** [comment]
@qaisjp Although drupal may be a bit extreme for this, it might make sense on two fronts;
- The views module is amazing, and should save us hours of work.
- Might be able to integrate it into http://blogs.love2d.org/, seeing as that's already a up and maintained instance of drupal specifically for the love community. It might even grow some more attention.

**Comment by qaisjp** [comment]
I was going to suggest using AngularJS with a API plugin (Restangular or http://www.breezejs.com/) for the web frontend since it's really light and fluffy. I'm AngularJS (http://angularjs.org by Google) and Restangular right now and I can say it's made my life a whole lot easier.

**Comment by qaisjp** [comment]
I'll try and have a go at creating a website.

**Comment by leafo** [comment]
You should do everything in Lua and build it with this: http://leafo.net/lapis/ :smiley:

**Comment by qaisjp** [comment]
Did you bloody make that? Bloody hell bloody epic. wait a minute, YOU made moonscript? huge fan here!

**Comment by josefnpat** [comment]
Talking to @leafo, the vapor platform might marry really well for a generated `games.json` from itch.io.

I would still like the platform to allow for sites other than itch.io, but I think our docs should reflect a preference for itch.io

**Comment by qaisjp** [comment]
itch.io looks more like a promotional service for Indie games than for something like vapors. Hand coding seems better, perhaps copy Indiegame.com
I'll post The dashboard at the site  later (i'm a registered developer at the website)

**Comment by josefnpat** [comment]
vapor.love2d.org
