### ISSUE TITLE
Delete button to delete games

### ISSUE THREAD

**Issue by Germanunkol** [josefnpat/vapor#72]
There has been talk about canceling a download, but I think it would also be important to be able to delete an already downloaded game.

Optionally, "savedgames" and settings could be deleted as well - this would require the games.json to hold information about the game-id (the folder name of the folder used to store the game data)
This would be a great step forward, I believe - because at this point there is no proper way of uninstalling love games - Vapor could change that.

**Comment by josefnpat** [comment]
Currently you can delete games with the "delete" or "backspace" key.

A delete button is on the roadmap for the new UI interface as designated in #70 :)

As for saved games, all one would have to do is to inspect the t.identity (or generate if not set), but isn't love sandboxed to prevent the user from deleting random folders?

**Comment by josefnpat** [comment]
If you can give me a way to delete game settings, I would think that would be something to add to vapor, e.g. "Shift Delete" and a modal dialog for the loveframes version that says, "What would you like?" => "Delete Game","Delete settings","Both","Nevermind"

I'm going to leave this ticket open until we can figure out if deleting other t.identity games settings is possible.

**Comment by josefnpat** [comment]
01e188f30a7ab29d762b1978a101591b36643509
