### ISSUE TITLE
Discussion: Use public mirrors, or unify as one service

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#75]
So i'm at a crossroads here.

This ticket relates to #7 and #68.

One thing that would be nice is to have folks mirror data for vapor.

There would be an `update.php` script, and when I update, I could hit that script to update all the public mirrors.

Then the clients could choose the best mirror, allow users to select mirrors, or even just choose mirrors at randomly.

On the other hand, it would be nice to get some metrics, and short of hitting a centralized server everytime a download is initialized, these two options seem rather mutually exclusive.

As mentioned in #44, it would also be nice to have some statistics which might be nice to include in the latter option.

Perhaps we could do some brainstorming here, and get some ideas on how to solve both of these problems, or at least why we should pick one over the other.

**Comment by Germanunkol** [comment]
My two cents:

Right now I don't think you need a list of mirrors.
I don't think the traffic will explode in the near future. If this tool ever replaces the rubber piggy (which I strongly encourage!) then maybe this changes and more mirrors would be useful.

My idea would be:
When a new game is added, the update.php pulls the game into one main server. The clients always try to get the game from the original servers (the ones that are used right now, where the developers have hosted the irgame) and only if that doesn't work (wrong hash, unreachable etc) the main server is contacted and the game is pulled from there.

This has a large advantage: If you should ever need to add more mirrors, the old structure would not break. So people with a newer version of the client would be able to choose mirrors that replace what I called "main server" above. But older versions of the tool would still work. So it would be easy to switch to a multiple mirrors environment later on, if the need arises.

**Comment by qaisjp** [comment]
I think the best method is to not allow developers to host their own games. If issues about "stealing code" arise, then they should understand that because love2d and vapor is completely open source (I assume the website will be open source too, just some authentication salts are not posted publicly).

Any .love files will be stored somewhere in a GitHub repository or in an Amazon EC2 dedi (or even a private dedi). All games stored in a .love has to have a license applied to it, even if it is one of those very restrictive CC licenses.
The system will automatically add the .love to a repository called github.com/love-vapor/games (vapor is an organisation), in a directory called repo:/games/[author_name]/[game_name]/game.love and LICENSE
LICENSE sets the license of the .love file, game.love contains the game file.

games.json will be scrapped, this prevents love from downloading a very large file. instead, a MySQL database will be used.
A list of tables: users, permissions, games
"uid" key will be a secondary key in permissions and games (im not sure if its called a secondary key, but it has a main reference to the users in the "users" table)

A PHP or other @leafo's MoonScript webserver will be used to act as an api to handle the interaction between the MySQL database and vapor.love. the API will output json. For example, domain.com/game/9 will output json containing individual information. but domain.com/game/1,9,8 would return multiple information in one json file. allowing for a reduced bandwidth usage.

Instead of hosting files on your own repository, you allow hosting files in people's own github/bitbucket repository.

All games can be added via a dashboard on a website.

**Comment by leafo** [comment]
Another approach is that I can make a vapor api on http://itch.io. People can upload their game there, add then add it to a collection in order to make it available for downloading through vapor. I already have infrastructure in place for hosting files and collecting statistics about downloads. Files are served through google cloud storage so they're reliable and have fast download speeds.

I also have payment infrastructure in place, so if anyone would want to sell their game on vapor then we could make it happen :thumbsup:

**Comment by josefnpat** [comment]
Thanks for weighing in guys, I need to give this some thought, as I would love to have my cake and eat it too.

**Comment by Bobbyjoness** [comment]
I think a central server and one unified service would be the best way to go. This way josefnpat would be able to have more control and if paid games were ever added maybe make a donate to LOVE fee and maintenance fee be there.

**Comment by pablomayobre** [comment]
Well I would prefer using itch.io, but that is my personal preference. I think it already exists, has everything that is needed and has a wide user base. The only problem being the games that are not in there...

**Comment by Bobbyjoness** [comment]
A main server to upload games too has many benefits. The most current one I just thought of is post processing. If we wanted to automatically add certain things to games we would be able to. For example compat layers. Sense I don't think compat layers are going to go away any time soon.

**Comment by pablomayobre** [comment]
Please DONT!

**Comment by Bobbyjoness** [comment]
Or any other features if they may arise. Another example testing the games ourselves.

**Comment by Bobbyjoness** [comment]
itch.io allows any games to be uploaded if that same process happens with Vapor then Vapor will soon be full of crap.

**Comment by pablomayobre** [comment]
Why wouldnt itch.io allows us to do that? After all we have the game.json file, and a Vapor API (hipothetical)

**Comment by Bobbyjoness** [comment]
Having itch.io as an extra source will be cool. But having own set up would be nice too. If we ever need anything itch.io won't give then we can just do it ourselves. So developing our own system along side itch.io will help us if that time ever comes.

**Comment by pablomayobre** [comment]
Uhm what else would we need? downloads, paying, users, our own api... Plus it is not like we cant use our own stuff when needed, we can still use our server, but itch.io handles most of the stuff, and leaves the rest of the neat things to us

**Comment by Bobbyjoness** [comment]
Flexibility is a good thing to have. It would suck if at one point we do need something but can't do it because it would require a lot of new services we never made.

**Comment by pablomayobre** [comment]
What I mean is that itch.io doesnt replace those services, those services can still exist and coexist with itch.io, using itch.io as the BIG base server is just the best way to go, since the basic stuff is already there.

**Comment by Bobbyjoness** [comment]
Well itch.io would have to provide us with a private api I would assume.

**Comment by Bobbyjoness** [comment]
For example our vapor site will upload to both it and itch.io rather than the other way around. Because people may mistake vapor as a client for all games and mess it up by adding non Löve games. Unless itch.io checks that for us.

**Comment by pablomayobre** [comment]
Well I think itch.io should check, and Vapor should approve before it appears in Vapor

**Comment by leafo** [comment]
There's already an API for viewing game files and downloading them. Would be glad to provide any other support you need. https://github.com/leafo/itchio-app/blob/master/itchioapi.cpp

**Comment by qaisjp** [comment]
@Bobbyjoness, well, I think that uploading directly in vapor would not be a
feature. Rather, one uploads to itch.io, and there could be a tiny setting
that takes a .love file and allows it to be accessed through vapor. Of
course, this could be implemented vapor-side, after uploaded to itch.io,
you fill in your game details to the vapor website. The vapor website will
use the api to check if it's a love game and if it is, automatically add it
to the vapor catalogue.

I think you're just making things too complicated ;)

**Comment by qaisjp** [comment]
@Bobbyjoness, well, I think that uploading directly in vapor would not be a
feature.

It would go something like this:
- upload to itch.io
- on the vapor authoring website, you copy the itch link
- vapor website does checks to see if a .love file is available (if multiple love files, ask user)
- website adds the itch game ID to the vapor catalogue

I think you're just making things too complicated ;)

**Comment by pablomayobre** [comment]
Well actually that is rather fast, you just give your itch.io game id and vapor verifies internally then it's done... sounds good to me

**Comment by josefnpat** [comment]
_contextual note: vapor2 will have a vapor-ui (front-end) and a vapor-core (library)_

My plan for vapor2 is to do the following:

1) Provide to users a default set of `source`s available when distributing vapor release. (The initial release would have `vapor.love2d.org` source enabled by default)
2) Provide a drupal site that would allow users to upload games for the vapor.love2d.org source.
3) Use said drupal site to also maintain framework information for the vapor.love2d.org source.
4) Allow the users to add&|enable other sources via `vapor-ui`, like a processed itch.io api to match the defined `source` structure)

This way, we can control the curators (e.g. the vapor-dev team, and itch.io by default) but then others can offer to curate games and framework packages as third parties.

This might open some doors to other communities who have similar executable package patterns like LÖVE. (e.g. [executable] [game file])

@leafo - When vapor2 gets closer to release, how would you feel about detecting if a file ends in a `.love` and asking users on itch.io if they would like to submit to itch.io's vapor source list, and then asking a few more details?

**Comment by qaisjp** [comment]
Doesn't the drupal site make itch.io obsolete for hosting? Or am I mistaking this for a standalone website (rather than a website that in the backend that deals with itch.io)

**Comment by Bobbyjoness** [comment]
Yay, we reached a verdict.

**Comment by Bobbyjoness** [comment]
@qaisjp having other sources can allow users to get other games. For example if the official source bans adult content then someone can upload to another source with less restrictions. That's the only benefit I see.

**Comment by Bobbyjoness** [comment]
Not saying I want adult content. Just an example.

**Comment by qaisjp** [comment]
Oh, multiple sources is definitely a cool option. I was thinking that there would be only one way. This would definitely be a great option for those that don't want to go on itch.io and set up a full page for their game, but would just like it to be in the vapor catalogue.

**Comment by josefnpat** [comment]
@qaisjp One could argue that using itch.io makes a drupal site obsolete for hosting.

The idea is by providing different sources, we can allow users to choose different curation systems.

I can see this being useful in a few ways:
- People like/don't like how vapor curates.
- People like/don't like how easy it is to get games on itch.io.
- A developer would like a source to test with locally.
- A developer would like to provide a UI that they can use to distribute their own game collections with
- A developer would like to have a stable and a testing version available to users.

vapor2 is going to be all about having your cake, and eating it too.

**Comment by leafo** [comment]
@josefnpat I'd most likely rather have that information collected and part of itch.io's database. You should come up with a list of the additional stuff you would need so I can see. Avoiding an addition submission step would be nice.

**Comment by josefnpat** [comment]
@leafo The "itch.io vapor source list" would be fully controlled by you and your servers! All of the metadata associated with the content will be on your servers for your "source" so to speak.

**Comment by Bobbyjoness** [comment]
But some people may not want their games available on 3rd party clients or sites so I think an extra submission step would be cool. Or at least a checkbox.

**Comment by qaisjp** [comment]
:clap: :cake: :+1: 

@Bobbyjoness he means that instead of having to also go to the vapor site to add it, you press a button on itch.io
(on another note, good job on reviving a two year old issue :))

**Comment by leafo** [comment]
@josefnpat Okay. Instead of a "Submit your game to vapor" page, I think a better experience would be a "I'm a love2d game checkbox" and then a tooltip about how it will be available on vapor. But that depends on the metadata you'll need.

**Comment by josefnpat** [comment]
@leafo Something along those lines should be perfect. When I get the preliminaries done, I will make a ticket about it, and ping you in it!

**Comment by Bobbyjoness** [comment]
@qaisjp I brought vapor back to life so your welcome lol.

**Comment by leafo** [comment]
Great,  my plans are to add detail pages for engines and tools on itch.io, and they would double as community hub pages. So love2d, aseprite, etc. would have a page on itch.io and you can browse the games that use the respective tool. Additionally I'll have sub flags for specifying exact versions. From the game edit page you'll add the tools you've used like you would add a tag. That should provide a decent level of classification to add the vapor api endpoints.

**Comment by Bobbyjoness** [comment]
Can Löve get front page and be the first community page? Drive people to Löve lol

**Comment by qaisjp** [comment]
@leafo Sweet, although maybe a "I'm a love2d game checkbox and I want it on vapor" checkbox, leaving the option to actually publish on vapor to them?

**Comment by Bobbyjoness** [comment]
Well tbh that might show favoritism he can't really do that for everyone who requests. Maybe and "Extras" drop down would be cool.

**Comment by Bobbyjoness** [comment]
That's way he can just add whoever to the list

**Comment by qaisjp** [comment]
Hmm....? I'm just saying that itch.io detects it's a love game, and gives the option to add it to vapor.

Not sure what you're on about @bobbyjoness

**Comment by Bobbyjoness** [comment]
Idk lol. If for example multiple 3rd party clients want to have access to itch.io as a .love source. It would be convenient for him to just have an extras drop down. Idk. Itch.io isn't what I'm working on. #vapor-dev #teamVapor lol

**Comment by qaisjp** [comment]
Well vapor is the official love2d client and other clients have access to the api.

**Comment by Bobbyjoness** [comment]
Its not official

**Comment by Bobbyjoness** [comment]
Unless I missed a forum post somewhere. If it was official it would have its own sub forum.

**Comment by qaisjp** [comment]
Please stop double posting, [and this](http://vapor.love2d.org)

**Comment by Bobbyjoness** [comment]
Sorry I'm on mobile so its difficult to edit my posts.

**Comment by pablomayobre** [comment]
It is official, just not mainstream yet.

On the topic, I think that what @josefnpat proposed is fine.

About itch.io, I think that if you are gonna specify framework and LÖVE will be an option, you could expand a checkbox that says "Submit game to Vapor", the problem is as @Bobbyjoness said that this shows favoritism and maybe other clients will want to have their own checkbox in there (say GameMaker, Unity or something like that) and have access to your data.

About supporting other executable packages with patterns like love ([executable] [game file])

I think that is nice but will need some alerts to tell the user the executable is not LÖVE so it is not tested nor verified by Vapor, it may contains virus and all that stuff, plus legal stuff (I guess this same stuff applies to custom LÖVE builds too).

Luckily my compat layer will fit perfectly in this pattern so no problems with that (will be able to reduce the number of executables with Cube whenever you need standard LÖVE builds)

Well sorry for the long comment!

**Comment by josefnpat** [comment]
@Positive07 Might make sense to add that warning on the UI when someone adds a new source. Good idea.

**Comment by pablomayobre** [comment]
:+1:

**Comment by josefnpat** [comment]
I think the vapor1.x outline properly takes care of the concerns in this issue!
