### ISSUE TITLE
The current "coverflow" is terrible.

### ISSUE THREAD

**Issue by qaisjp** [josefnpat/vapor#78]
It doesn't flow, to be perfectly honest. The transition between items is way too choppy or fast between individual items. Here is a nice video of a coverflow that would be appropriate.

http://www.youtube.com/watch?v=t2XlIQqo_XA&feature=em-upload_owner

**Comment by josefnpat** [comment]
Feel free to write a pull request for `ui.cover` and `ui.header` found in `src/core/ui.lua`.

**Comment by josefnpat** [comment]
Closing in favor of the more constructive #87
