### ISSUE TITLE
Single or multiple games.json ?

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#85]
I was wondering why this project uses a single games.json file, to be edited by everyone who wants to submit a game ?

I was thinking of a folder holding all *.json files each single one related to a specific game. So that, to submit a new game, the author would basically just write his own *.json, and then pull it to this repository. 
As [Luarocks](http://luarocks.org/) or [Moonrocks](rocks.moonscript.org) with the [rockspec format](http://luarocks.org/en/Rockspec_format).

Well, I am not saying this is the best option here, as I am not familiar with the ins and outs of dealing with large *.json files. I am just raising the question.

Best regards,
Roland.

**Comment by qaisjp** [comment]
Vaporrocks. Nah jk, MySQL should be used.

**Comment by Yonaba** [comment]
Vaporrocks... It is a bit long, but I like that!

**Comment by qaisjp** [comment]
I was joking... I think using lapis to make a MySQL dashboard with
statistics would be a good idea. Obviously statistics can be manipulated,
so cloning the App Store wouldn't be feasible.

**Comment by josefnpat** [comment]
@Yonaba 

Considering vapor needs to load all of the data on start up anyway, it makes sense to keep it in one json file.

Also, consider the fact for each file you download, you are also downloading the http header. The entire json file is ~18K for 27 entries (~0.66K per entry). The lower limit for a basic apache server is about 8K.

Thus,

Storing each json file as it's own: (~0.66K + ~8K)_entries
Storing all entries as one json: (~0.66K)_entries + ~8K

You can see quicky we can keep bandwith very very low by storing everything in one json file;

![x](http://i.imgur.com/Hpjmnvo.gif)

On the other hand, if we want to have external json files (e.g. load one from itch.io) this might be a good idea, but I unless I've missed something, I don't think it's a good idea to do it on a per-game basis.

**Comment by Yonaba** [comment]
Oh, I love graphs. :+1: 
Well, that is pretty much explicit...I can now close that issue.
