### ISSUE TITLE
Submitting a game : Ouroboros

### ISSUE THREAD

**Issue by Yonaba** [josefnpat/vapor#88]
I liked this one very much: [Ouroboros](https://github.com/Moe-/OuroborosJump).
It was made for [GGJ'12](http://archive.globalgamejam.org/2012/ouroboros-adventures-sir-wayne-finley).
Maybe a good candidate for Vapor ?

Best regards,
Roland.

**Comment by josefnpat** [comment]
The `conf.lua` in the repo doesn't mark any version for the game, and I can't even get the game to run on `0.8.0`. Were you able to?

**Comment by Yonaba** [comment]
My bad. I played it a long time ago, and when I came across this that afternoon, I quite forgot it was made for Löve `0.7.2`. Anyway, it can be easily made compatible with `0.8.0`. As far as I can see, only some lines related to the ParticleSystems API have to be updated.
I can fix this and send a pull request the the original repository.
Once it is accepted (and merged), I can let you know right here. :+1:

**Comment by josefnpat** [comment]
Fantastic!

**Comment by Yonaba** [comment]
Can you please let me know if [those changes](https://github.com/Yonaba/OuroborosJump) work for you ?

**Comment by josefnpat** [comment]
![x](http://i.imgur.com/ZbYEBBU.png)

**Comment by Yonaba** [comment]
Are you using a joystick ? Seems so.
Well, this error should related to the original authors, 
For some reason, `love.joystick.getAxes()` returns `nil` (at line 82), hence the error when trying to compare (at line 86) `leftRightAxis` with `joysticksensitivity` (which is set to 0.3).
I can eventually take a closer look at this (when I find my joystick, hopefully), but it definitely goes out the Löve 0.7.2 -> 0.8.0 port, IMHO.
That said, it seems the game runs fine using the keyboard, can you check ?

EDIT: [Hackey fix for joysticks](https://github.com/Yonaba/OuroborosJump/tree/c5d65df00d99740931c90fbe6b207e3bd5ca1437). :+1: Should hopefully work fine.

**Comment by josefnpat** [comment]
These fixes work great! And on top of this, it's a solid platformer.

Are we able to contact the authors? I know it's from 2012, but it's a rather attractive game.

If we can't, I can just host it myself, and point to "Attribution-Noncommercial-Share Alike 3.0"

**Comment by Yonaba** [comment]
Great, let's consider this as our "Plan B".
I sent a [pull request](https://github.com/Moe-/OuroborosJump/pull/1) to the original repository.

**Comment by Yonaba** [comment]
Good news, [OuroborosJump](http://www.brightidea.eu/?page_id=84) is ready to be added to Vapor. :+1:
