### ISSUE TITLE
The Binding of Crate Box

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#89]
Contact author for https://love2d.org/forums/viewtopic.php?f=5&t=53185

**Comment by josefnpat** [comment]
http://love2d.org/forums/viewtopic.php?f=5&t=53185&start=10#p131393

Sure, go ahead. (if I have to do something then I'll do it next week or so)

_suck it @bartbes_

**Comment by a327ex** [comment]
Hey!

name: The Binding of Crate Box
sources: http://notmagi.me/downloads/The%20Binding%20of%20Crate%20Box.love, https://dl.dropboxusercontent.com/u/17437327/The%20Binding%20of%20Crate%20Box.love
(or you could host it if you want to)
author: adnzzzzZ
website: notmagi.me
description: The Binding of Isaac + The Super Crate Box, woo! Are you a bad enough dude to kill all the bad dudes?
image: http://i.imgur.com/u35YRgM.png
