### ISSUE TITLE
Change icon set to FamFamFam

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#9]
```
 qaisjp commented 6 minutes ago 
How about FamFamFam www.famfamfam.com/lab/icons/
Just a wild suggestion.
```

Might be nice, but can we redistribute CCSA2.5 under GPLv3?

**Comment by josefnpat** [comment]
@qaisjp

**Comment by qaisjp** [comment]
You can license subcontent under other things, so I can run a public domain project that contains CCSA2.5 icon (the icons have a license, rest of code don't). Just prop the license in the /assets/famfamfam/ folder (or equivalent).
I'm not a lawyer so don't trust me on this.

**Comment by josefnpat** [comment]
I did a quick test of this, and this is what I got;

http://i.imgur.com/JPAf0JT.png

The smaller size is definitely a plus (and we ought to consider shrinking down our current icons), but I had troubles finding good icons in famfamfam for everything else. I think we need to keep looking for a better icon set.
