### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by josefnpat** [josefnpat/vapor#99]
https://github.com/josefnpat/vapor/commit/cf36937eb59586847cb759973e479f1d5ffa3e4b#commitcomment-4049621

@qaisjp mentions that i have some duplicated code here. Ought to make these functions. I'll get to this as soon as I have time, unless someone beats me to it.

**Comment by Yonaba** [comment]
I am definitely missing something. I see nothing like repeated code in line [20-21](https://github.com/josefnpat/vapor/blob/master/src/main.lua#L20-L21) / [23-24](https://github.com/josefnpat/vapor/blob/master/src/main.lua#L23-L24) in [main.lua](https://github.com/josefnpat/vapor/blob/master/src/main.lua) ?

**Comment by qaisjp** [comment]
Oops! http://qs.lc/e7i4
